[package]
name = "ascii_art_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.9"
nannou = "0.19.0"
rand = "0.8.5"
